#!/bin/sh

##
# Git diff for SQLite databases
##

if [ -z "$DIFF" ]
then
	DIFF=diff
fi

SQLITE=sqlite3

if [ -z "$1" ]
then
	export GIT_EXTERNAL_DIFF=$0
	git diff
else
	tmp="`dirname "$2"`"

	file "$2"|grep 'SQLite 3.x' >/dev/null 2>&1
	
	if [ $? -ne 0 ]
		then
		$DIFF "$2" "$5"
		exit 0
	fi

	$SQLITE "$2" .dump >"$tmp/olddump.txt"
	$SQLITE "$5" .dump >"$tmp/newdump.txt"

	$DIFF "$tmp/olddump.txt" "$tmp/newdump.txt"
	rm -f "$tmp/olddump.txt" "$tmp/newdump.txt"
fi
